# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "k2bKmSWMNCul5b6nuFuUCyqoE2WAG74MeuH8clT8k8bHw3fBw3InMbqpeMeikUfXYT0KZ1gexBPzt06g51DLn99QEVfb4erXwLNmJ9E/dZSIkH08I6ZQMHb318U+UpkUdGKBjPho0AQ/0oIUyU7GwAcLolgoux1sYbIiwlQJcMganv+W5+TefvAliUvYqwAVrVby8BKwAVCWtfiNtNUDcPtOtAlyW8wFY4s+P0T3dGSMxvw0YPG+wOzd8ga8Z+sz9UUzdOCiCOYZaT/lx0Z7Ri8hdVq97t+64q/3s+Sq4Id0nWLzyQepZ5xIbP2dPCN/PJYftUk3RzDL7eR1tV6v7hoSQUjiY+k5m3PSzXKDWHqWwJ/8GHYrUZRxNWifdyA8y/fe+sy23ECEFR88fnl0w/d/NjFPLpvKSRVeX94lufSBtluCgqE1dXAOWEkUHJkgSo7v+pOTgkpiX8mq644yrbwwLeTMZQPuK31RWlWZgu0ymffukAaA6z8tfVr2NLMJ+ct8zJREzEQiqsvIbvvAgvzVCaNnFsUe8AKb7zqy6BMcTUHZoe5aKViRxsaO+iIlhVb84nQ1GxdLo8J4Do35/LbCT8ETIxLVs3jqX31hT0l5wAl/sDH2+i3CJjY52xgLmgu/CmEVPCMxdLW4DkhwKrn/3WWpG8+4GAOjmsFM5Ro="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
