travis:
  secure:
    BINSTAR_TOKEN: CZIazyPbh3KJ+HEbMZFlBqcxB+Dvj2rUPJttKK5Jv9wUmlooBHkLiQ+O0ytU7uLDiiFt4TVBXiM5JzJgQFzCqoFwk+FVpn2sCqK0r3TgKaatBqblYSyhV8Pll0Dts6s/Hs0tLyRmSIvkCyzf6FEwQchzRR/xe5hDWEIV5ledjsudlf8EVeVd8WRR3/1BpAotYUK//xwRAyo7fKtmyTBZ3TvmMiw7faesgXTYHmS0TKIyGpih+5KPAHRi08DaGUXYREf+ndlbMwu5sNRCvsiQMikB7Rn/JD9i6JI2hsdQuirvT6hR/hTkAZtuSG7nPTtd7vHSe14z7jpmkg7ptEV9nTDyXvoDnxZYtS8ItaebgdnMYkEYxd62eYGpSlb6amikbVBkr/p+NTyc7TossilKDiVewddloZou+HWwgHC04eGHy7rtEvlJ9czcyuO0VE+DvCE9L7UGfkEhe6LZmDGN/RdK7q3fsFsY2R56LZZqLfzVEZH5yS55R/+0A2JSovsXr7OZZgvf/1JiTfho7zdTF59q5yelxx/+PCDoBh1Ys2EOWBaTG5A71prWubZ7hZn8RYW8ggwcR1S3aQEvwhWSb3Pi3DtouR15M5AEdhq1e4AdHeLINII09QH+ZBxSNV24p9nsNpWm1xeUp/te5PctuRuvraYvnSi8JPYzVF5a3sI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
