appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: k2bKmSWMNCul5b6nuFuUCyqoE2WAG74MeuH8clT8k8bHw3fBw3InMbqpeMeikUfXYT0KZ1gexBPzt06g51DLn99QEVfb4erXwLNmJ9E/dZSIkH08I6ZQMHb318U+UpkUdGKBjPho0AQ/0oIUyU7GwAcLolgoux1sYbIiwlQJcMganv+W5+TefvAliUvYqwAVrVby8BKwAVCWtfiNtNUDcPtOtAlyW8wFY4s+P0T3dGSMxvw0YPG+wOzd8ga8Z+sz9UUzdOCiCOYZaT/lx0Z7Ri8hdVq97t+64q/3s+Sq4Id0nWLzyQepZ5xIbP2dPCN/PJYftUk3RzDL7eR1tV6v7hoSQUjiY+k5m3PSzXKDWHqWwJ/8GHYrUZRxNWifdyA8y/fe+sy23ECEFR88fnl0w/d/NjFPLpvKSRVeX94lufSBtluCgqE1dXAOWEkUHJkgSo7v+pOTgkpiX8mq644yrbwwLeTMZQPuK31RWlWZgu0ymffukAaA6z8tfVr2NLMJ+ct8zJREzEQiqsvIbvvAgvzVCaNnFsUe8AKb7zqy6BMcTUHZoe5aKViRxsaO+iIlhVb84nQ1GxdLo8J4Do35/LbCT8ETIxLVs3jqX31hT0l5wAl/sDH2+i3CJjY52xgLmgu/CmEVPCMxdLW4DkhwKrn/3WWpG8+4GAOjmsFM5Ro=}
bot:
  automerge: true
