travis:
  secure:
    BINSTAR_TOKEN: ihQYT4Xf7YrfIA9SS2YdnjQ/B+Njn+rtWhFGMYc9Kc/evd6HxySF4U96VLDmANsxa7ftk9gHAM5Tajm4xM334uQ6m4+RXmpcaSq/xsBZmuU/6LK/AyJZktVQCCBLAI7g6bDSBJJnJ84EmwTlGrhHSx45qltxM/0ApmkqtadYIcY/SqDKhdMlmlGxkUoOxp4xYWLomjFO9EVBtu2AGikPdcGc8DrHyikOVgi22pvD+fZFedoMp030QmMIGcb0/LMKeLpVAsr9aKOrTGADHQS3MHbq4W/QRJuBwukWPqZQzmehmVngRNTfcLNOXDyX42dCvqMbZKMahdq4pqV5dxV0tWMTWJMgAue1X4YSoQrFxUAKFTz3A2dCJGbv2Gq0vV0gYFYDlCfF+y1bhjTy9jMiF+BoS4UGO/dV3Utiw97YSjZpX3VA7YjlZWoXgmcpI1HQmI5Oi7pufXLXod0GL9fEyNbyf/HOj1FSFNl6nNHneurkRVpKhJk0+9qU4vhVs63ZXaAGOjT3GYxjW49xHVDAB9qeC61IACDdXCC9zS05xTngek+QzsqFfQlm5+6it1YY/pGj34HA062PlgQdaee/tsV2atDXvQJA1rNFRXgPaBbKWSpjzCjWp3A9zHbU2dTxBs408UR4lMaNuRD3Y/AuOwArVZUBbJyDSWP8kqw1pQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
