travis:
  secure:
    BINSTAR_TOKEN: Y7KaiyWlyK9oLNro9Ds1bKlb4u27tcGo+YLUiPuviDqXPSpnClEmvuK2KgTQdHIsprU1FTmM0yK3+CmB4tl4tI68P2aNnyQJOpjqJlpZr19Ac4pXFHf/GfoUG8Oeh3j3Ns6bZigRCSFbWjUJUhztFWJwUtNXk7G5fupVMPI/j55eYXtkXLIlmyWWSrTCtPvg9yH0aeyAElXMIpx2nzcGIG12ZU9IFR87+ksHc7k/VGYg8EFRpiwkRbC3xYMPm4q5jhWqClzGQwpVFroDzvZrp31WAVoR2zXabOGs1HADKcrqHa196fKoMFYrswAkevxpHnKq/iWAI0n/RoWVX+VmQG2HaeU5UKU7IPnZOk06pxg2LONyq6S+1xe+FqzwW3vAS/4jwaqmA913H9BTi57EjRkFjrnpDqSOBmiv0QOSC1iXJub2adyAGx2/RZG2o36//fK/rAt4nnn4yMc4OxYcaxupbEuAgPIvENxNN/d+3yI5JLtldMRpwSwuClQTYXkW2gGUh7AJAA98BUWOPJHHoGzIxbeclifrsoYTN69XP/m/2SUT7qUK/y4HYD2rbT4Nim0zeqZidrQUg/hCQz/H0/F26HGTYHH0S9y2WksLu4+/nfKKmg4OGXqSAkt9J2bTqoTUhYoQjJZfRifSX0IhZo+uI4V5cggeK9HAInqeBzI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
